name: Onin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51433
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002E3E'
    - '#BFB7A2'
    - '#435F6D'
    - '#AB8B80'
    - '#FFFFFF'
  brandStrength: 0.4375
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
