name: Onin
favicon: null
layout_spectrum: 0.254
typography_spectrum: 0.14809
title: Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002e3e'
    - '#bfb7a2'
    - '#435f6d'
    - '#ab8b80'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
