analytics: {}
color:
  brandColors:
    - '#002E3E'
    - '#BFB7A2'
    - '#435F6D'
    - '#AB8B80'
    - '#FFFFFF'
  brandStrength: 0.493243
  lightness: 0
  rhythmicContrast: 0.220439
  saturation: 0.6875
cta: {}
layout_spectrum: 1
name: Onin
opengraph: {}
purpose: []
typography_spectrum: 0.313345
