name: Onin
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002E3E'
    - '#BFB7A2'
    - '#435F6D'
    - '#AB8B80'
    - '#FFFFFF'
  brandStrength: 0.493243
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0.220439
purpose: []
